import { matches, participants, round } from '@/lib/demo-data';
import type { Profile } from '@/lib/types';

function statusCopy(profile?: Profile | null) {
  if (!profile) return 'Inicia sesión para participar.';
  if (profile.participantStatus === 'pending') return 'Tu cuenta está pendiente de activación por el administrador.';
  if (profile.participantStatus === 'blocked') return 'Tu cuenta está bloqueada.';
  return 'Jornada abierta: puedes guardar cambios hasta el cierre.';
}

export function RoundBoard({ profile }: { profile?: Profile | null }) {
  const canPlay = profile?.participantStatus === 'active';
  return <div className="space-y-5"><section className="card bg-gradient-to-br from-brand-50 to-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="status-pill bg-emerald-100 text-emerald-700">Abierta</span><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{round.name}</h1><p className="mt-1 text-sm text-slate-600 sm:text-base">Límite: 21/08/2026 20:00 · 14 partidos + Pleno al 15</p><p className="mt-3 rounded-2xl bg-white/80 p-3 text-sm font-semibold text-slate-700">{statusCopy(profile)}</p></div><button className="btn hidden sm:inline-flex" disabled={!canPlay}>Guardar pronósticos</button></div></section><section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-3"><h2 className="px-1 text-xl font-black">Boletín de la jornada</h2>{matches.map(m=><article key={m.id} className="card"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-slate-900 text-sm font-black text-white">{m.order}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="status-pill bg-slate-100 text-slate-600">{m.division}</span>{m.is_pleno ? <span className="status-pill bg-amber-100 text-amber-700">Pleno al 15</span> : null}</div><h3 className="mt-2 text-lg font-black leading-tight">{m.home_team} - {m.away_team}</h3><p className="text-sm text-slate-500">{m.competition} · {new Date(m.starts_at).toLocaleString('es-ES')}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2">{['1','X','2'].map(p=><label key={p} className="flex min-h-14 cursor-pointer items-center justify-center rounded-2xl border-2 border-slate-200 text-xl font-black has-[:checked]:border-brand-700 has-[:checked]:bg-brand-50 has-[:checked]:text-brand-700"><input className="sr-only" name={m.id} type="radio" disabled={!canPlay}/>{p}</label>)}</div><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex items-center gap-2 rounded-2xl bg-slate-50 px-3 py-3 text-sm font-bold"><input type="checkbox" disabled={!canPlay}/> Partido destacado</label>{m.is_pleno ? <input className="input sm:w-32" placeholder="Resultado exacto: 2-1" disabled={!canPlay}/> : null}</div></article>)}</div><aside className="space-y-3"><h2 className="px-1 text-xl font-black">Clasificados</h2>{participants.slice(0,8).map(p=><div key={p.id} className="card flex items-center justify-between"><div><p className="font-black">{p.displayName}</p><p className="text-sm text-slate-500">{p.teamName}</p></div><span className="status-pill bg-emerald-100 text-emerald-700">{p.status}</span></div>)}</aside></section><div className="fixed inset-x-0 bottom-[76px] z-20 px-3 sm:hidden"><button className="btn w-full text-base" disabled={!canPlay}>{canPlay ? 'Guardar pronósticos' : 'Solo activos pueden pronosticar'}</button></div></div>;
}
