import { requireUser, profileFromFirestore } from '@/lib/auth';
import { firestoreRest } from '@/lib/firebase';
import type { Profile } from '@/lib/types';

type FirestoreDoc = { name?: string; fields?: Record<string, { stringValue?: string; doubleValue?: number; integerValue?: string; timestampValue?: string }> };
type FirestoreList = { documents?: FirestoreDoc[] };

async function loadRealUsers() {
  const { data } = await firestoreRest<FirestoreList>('users?pageSize=200&orderBy=displayName');
  return (data.documents ?? []).map((doc) => profileFromFirestore(doc)).filter(Boolean) as Profile[];
}

export default async function Clasificacion(){await requireUser();const rows=(await loadRealUsers()).sort((a,b)=>(b.moneyWon??0)-(a.moneyWon??0)||a.displayName.localeCompare(b.displayName));return <div className="space-y-5"><div className="card"><h1 className="text-3xl font-black">Clasificación</h1><p className="text-slate-600">Solo se muestran usuarios reales registrados en Firestore.</p></div>{rows.length===0?<div className="card text-center"><h2 className="text-xl font-black">Todavía no hay usuarios registrados</h2><p className="mt-2 text-sm text-slate-600">Cuando haya usuarios reales en Firebase aparecerán aquí.</p></div>:<><div className="grid gap-3 md:hidden">{rows.map((p,i)=><article key={p.id} className="card"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase text-brand-700">#{i+1}</p><h2 className="text-xl font-black">{p.displayName}</h2><p className="text-sm text-slate-500">{p.teamName ?? 'Sin equipo'}</p></div><p className="text-3xl font-black">{p.moneyWon ?? 0}€</p></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-2xl bg-slate-50 p-2"><b className="block">{p.role}</b>Rol</span><span className="rounded-2xl bg-slate-50 p-2"><b className="block">{p.participantStatus}</b>Estado</span><span className="rounded-2xl bg-slate-50 p-2"><b className="block">{p.moneyWon ?? 0}€</b>Dinero</span></div></article>)}</div><div className="card hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left text-slate-500"><th>Pos</th><th>Participante</th><th>Email</th><th>Equipo</th><th>Rol</th><th>Estado</th><th>Dinero</th></tr></thead><tbody>{rows.map((p,i)=><tr key={p.id} className="border-t"><td className="py-3 font-black">{i+1}</td><td>{p.displayName}</td><td>{p.email}</td><td>{p.teamName ?? 'Sin equipo'}</td><td>{p.role}</td><td>{p.participantStatus}</td><td>{p.moneyWon ?? 0} €</td></tr>)}</tbody></table></div></>}</div>}
